import { CustomerItem } from '@/src/types';

export const customerSummary = {
  totalCustomers: '2,418',
  activeCustomers: '1,840',
  repeatCustomers: '924 (38.2%)',
  atRiskCustomers: '142',
  averageRetentionRate: '76.1%',
  averageCustomerLifetimeValue: '₹7,850',
};

export const mockCustomersData: CustomerItem[] = [
  {
    id: 'cust-1',
    name: 'Vikramaditya Rao',
    email: 'vikram.rao@techcorp.in',
    phone: '+91 98450 12891',
    orders: 14,
    totalSpend: 48900,
    lastPurchase: '2 days ago',
    status: 'VIP',
    preferredCategory: 'Computing & Peripherals',
  },
  {
    id: 'cust-2',
    name: 'Priya Venkatesh',
    email: 'priya.v@zenithdesign.io',
    phone: '+91 99002 44102',
    orders: 9,
    totalSpend: 31200,
    lastPurchase: 'Today',
    status: 'VIP',
    preferredCategory: 'Audio & Acoustics',
  },
  {
    id: 'cust-3',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    phone: '+91 97311 90234',
    orders: 6,
    totalSpend: 18450,
    lastPurchase: 'Today',
    status: 'Active',
    preferredCategory: 'Electronics',
  },
  {
    id: 'cust-4',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@fintechhub.com',
    phone: '+91 98860 33819',
    orders: 5,
    totalSpend: 14200,
    lastPurchase: 'Yesterday',
    status: 'Active',
    preferredCategory: 'Accessories',
  },
  {
    id: 'cust-5',
    name: 'Deepak Verma',
    email: 'deepak.verma88@outlook.com',
    phone: '+91 94481 65720',
    orders: 4,
    totalSpend: 9800,
    lastPurchase: '3 days ago',
    status: 'Active',
    preferredCategory: 'Computing & Peripherals',
  },
  {
    id: 'cust-6',
    name: 'Sunil Chettiar',
    email: 'sunil.c@innovatech.org',
    phone: '+91 98200 48192',
    orders: 8,
    totalSpend: 28400,
    lastPurchase: '58 days ago',
    status: 'At Risk',
    preferredCategory: 'Electronics',
  },
  {
    id: 'cust-7',
    name: 'Meera Nambiar',
    email: 'meera.nambiar@yahoo.co.in',
    phone: '+91 98451 90211',
    orders: 7,
    totalSpend: 22600,
    lastPurchase: '64 days ago',
    status: 'At Risk',
    preferredCategory: 'Audio & Acoustics',
  },
  {
    id: 'cust-8',
    name: 'Karan Malhotra',
    email: 'karan.m@startuplabs.in',
    phone: '+91 99401 22910',
    orders: 5,
    totalSpend: 17900,
    lastPurchase: '72 days ago',
    status: 'At Risk',
    preferredCategory: 'Computing & Peripherals',
  },
  {
    id: 'cust-9',
    name: 'Harish Ranganathan',
    email: 'harish.r@chennailogistics.in',
    phone: '+91 94432 10874',
    orders: 2,
    totalSpend: 4200,
    lastPurchase: '115 days ago',
    status: 'Inactive',
    preferredCategory: 'Electronics',
  },
  {
    id: 'cust-10',
    name: 'Divya Agarwal',
    email: 'divya.agarwal92@gmail.com',
    phone: '+91 97110 54321',
    orders: 1,
    totalSpend: 1899,
    lastPurchase: '140 days ago',
    status: 'Inactive',
    preferredCategory: 'Mobile Gear',
  },
];
