import { ProductItem } from '@/src/types';

export const inventorySummary = {
  totalProducts: 142,
  inventoryValue: '₹18,65,000',
  lowStockCount: 4,
  outOfStockCount: 3,
  healthyStockRatio: '95.1%',
  turnoverRate: '4.2x / yr',
};

export const mockInventoryData: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'UltraSpeed USB-C Multi-Hub 7-in-1',
    sku: 'NOV-ACC-091',
    category: 'Accessories',
    price: 2899,
    stock: 0,
    threshold: 15,
    salesVelocity: '28 units / week',
    status: 'Out of Stock',
    supplierLeadTimeDays: 3,
  },
  {
    id: 'prod-2',
    name: 'SonicBass Noise-Cancelling Headphones',
    sku: 'NOV-AUD-104',
    category: 'Audio',
    price: 4999,
    stock: 0,
    threshold: 10,
    salesVelocity: '19 units / week',
    status: 'Out of Stock',
    supplierLeadTimeDays: 5,
  },
  {
    id: 'prod-3',
    name: '65W GaN Fast Charger Dual-Port',
    sku: 'NOV-ELC-220',
    category: 'Electronics',
    price: 1899,
    stock: 0,
    threshold: 20,
    salesVelocity: '34 units / week',
    status: 'Out of Stock',
    supplierLeadTimeDays: 4,
  },
  {
    id: 'prod-4',
    name: 'Ergonomic Vertical Wireless Mouse',
    sku: 'NOV-CMP-055',
    category: 'Computing',
    price: 1899,
    stock: 3,
    threshold: 12,
    salesVelocity: '14 units / week',
    status: 'Low Stock',
    supplierLeadTimeDays: 4,
  },
  {
    id: 'prod-5',
    name: 'Mechanical Gaming Keyboard RGB',
    sku: 'NOV-CMP-078',
    category: 'Computing',
    price: 3850,
    stock: 4,
    threshold: 10,
    salesVelocity: '11 units / week',
    status: 'Low Stock',
    supplierLeadTimeDays: 6,
  },
  {
    id: 'prod-6',
    name: 'Heavy Duty 4K Braided HDMI Cable (3m)',
    sku: 'NOV-ACC-032',
    category: 'Accessories',
    price: 799,
    stock: 5,
    threshold: 15,
    salesVelocity: '22 units / week',
    status: 'Low Stock',
    supplierLeadTimeDays: 2,
  },
  {
    id: 'prod-7',
    name: 'Smart WiFi LED Desk Lamp with Qi Charger',
    sku: 'NOV-ELC-341',
    category: 'Electronics',
    price: 2499,
    stock: 4,
    threshold: 8,
    salesVelocity: '9 units / week',
    status: 'Low Stock',
    supplierLeadTimeDays: 4,
  },
  {
    id: 'prod-8',
    name: 'MagSafe 10,000mAh Magnetic PowerBank',
    sku: 'NOV-MOB-012',
    category: 'Mobile Gear',
    price: 2299,
    stock: 42,
    threshold: 15,
    salesVelocity: '18 units / week',
    status: 'Normal',
    supplierLeadTimeDays: 3,
  },
  {
    id: 'prod-9',
    name: 'Aluminum Laptop Riser Stand (Foldable)',
    sku: 'NOV-ACC-110',
    category: 'Accessories',
    price: 1499,
    stock: 38,
    threshold: 12,
    salesVelocity: '15 units / week',
    status: 'Normal',
    supplierLeadTimeDays: 3,
  },
  {
    id: 'prod-10',
    name: 'True Wireless Studio Earbuds Pro',
    sku: 'NOV-AUD-088',
    category: 'Audio',
    price: 3299,
    stock: 55,
    threshold: 20,
    salesVelocity: '24 units / week',
    status: 'Normal',
    supplierLeadTimeDays: 4,
  },
  {
    id: 'prod-11',
    name: 'Smart Plug 16A Energy Monitoring',
    sku: 'NOV-ELC-109',
    category: 'Electronics',
    price: 999,
    stock: 64,
    threshold: 25,
    salesVelocity: '20 units / week',
    status: 'Normal',
    supplierLeadTimeDays: 3,
  },
  {
    id: 'prod-12',
    name: '1080p Ultra HD Streaming Webcam with Mic',
    sku: 'NOV-CMP-029',
    category: 'Computing',
    price: 2999,
    stock: 22,
    threshold: 10,
    salesVelocity: '7 units / week',
    status: 'Normal',
    supplierLeadTimeDays: 5,
  },
];
