import { SaleItem } from '@/src/types';

export const salesSummary = {
  totalSales: '₹8,42,000',
  averageOrderValue: '₹655',
  totalTransactions: '1,284',
  topCategory: 'Electronics (42%)',
  growthRate: '-14.8%',
  inStoreRatio: '68%',
  onlineRatio: '32%',
};

export const salesDailyTrend = [
  { day: 'Mon', sales: 118000, orders: 182 },
  { day: 'Tue', sales: 94000, orders: 145 },
  { day: 'Wed', sales: 106000, orders: 164 },
  { day: 'Thu', sales: 122000, orders: 188 },
  { day: 'Fri', sales: 148000, orders: 226 },
  { day: 'Sat', sales: 182000, orders: 274 },
  { day: 'Sun', sales: 72000, orders: 105 },
];

export const mockSalesData: SaleItem[] = [
  {
    id: 's-101',
    orderNumber: '#ORD-9842',
    date: 'Today, 14:32',
    customerName: 'Aarav Sharma',
    category: 'Electronics',
    items: '4K HDMI Display Dongle + 2m Nylon Braided Cable',
    channel: 'In-Store',
    paymentMethod: 'UPI',
    amount: 2499,
    status: 'Completed',
  },
  {
    id: 's-102',
    orderNumber: '#ORD-9841',
    date: 'Today, 13:15',
    customerName: 'Priya Venkatesh',
    category: 'Audio & Acoustics',
    items: 'Wireless ANC Earbuds Pro (White)',
    channel: 'Online Store',
    paymentMethod: 'Card',
    amount: 4299,
    status: 'Completed',
  },
  {
    id: 's-103',
    orderNumber: '#ORD-9840',
    date: 'Today, 11:40',
    customerName: 'Vikramaditya Rao',
    category: 'Computing & Peripherals',
    items: 'Ergonomic Mechanical Keyboard (Blue Switches)',
    channel: 'In-Store',
    paymentMethod: 'UPI',
    amount: 3850,
    status: 'Completed',
  },
  {
    id: 's-104',
    orderNumber: '#ORD-9839',
    date: 'Today, 10:22',
    customerName: 'Ananya Deshmukh',
    category: 'Accessories',
    items: 'Aluminum Laptop Riser Stand (Silver)',
    channel: 'Online Store',
    paymentMethod: 'NetBanking',
    amount: 1499,
    status: 'Processing',
  },
  {
    id: 's-105',
    orderNumber: '#ORD-9838',
    date: 'Yesterday, 19:50',
    customerName: 'Rahul Mehta',
    category: 'Electronics',
    items: 'Smart SmartPlug 16A with Power Metering (Pack of 2)',
    channel: 'In-Store',
    paymentMethod: 'Cash',
    amount: 1999,
    status: 'Completed',
  },
  {
    id: 's-106',
    orderNumber: '#ORD-9837',
    date: 'Yesterday, 18:14',
    customerName: 'Sneha Kulkarni',
    category: 'Mobile Gear',
    items: 'MagSafe 10,000mAh PowerBank Fast Charge',
    channel: 'In-Store',
    paymentMethod: 'UPI',
    amount: 2299,
    status: 'Completed',
  },
  {
    id: 's-107',
    orderNumber: '#ORD-9836',
    date: 'Yesterday, 16:05',
    customerName: 'Karthik Nambiar',
    category: 'Audio & Acoustics',
    items: 'Studio Monitor Studio Headphones 50mm Driver',
    channel: 'Online Store',
    paymentMethod: 'Card',
    amount: 5490,
    status: 'Completed',
  },
  {
    id: 's-108',
    orderNumber: '#ORD-9835',
    date: 'Yesterday, 14:20',
    customerName: 'Rohan Gupta',
    category: 'Electronics',
    items: 'Cat7 Shielded Ethernet Cable 15m (Defective Return)',
    channel: 'In-Store',
    paymentMethod: 'UPI',
    amount: 699,
    status: 'Refunded',
  },
  {
    id: 's-109',
    orderNumber: '#ORD-9834',
    date: '03 Sep, 2026',
    customerName: 'Tanvi Iyer',
    category: 'Accessories',
    items: 'Tempered Glass Screen Guard (Pack of 3)',
    channel: 'In-Store',
    paymentMethod: 'UPI',
    amount: 599,
    status: 'Completed',
  },
  {
    id: 's-110',
    orderNumber: '#ORD-9833',
    date: '03 Sep, 2026',
    customerName: 'Deepak Verma',
    category: 'Computing & Peripherals',
    items: 'Wireless Vertical Mouse 4000 DPI',
    channel: 'Online Store',
    paymentMethod: 'UPI',
    amount: 1899,
    status: 'Completed',
  },
];
